/* This file is automatically generated from
 * ../subversion-1.6.12/subversion/libsvn_fs_fs/rep-cache-db.sql
 * Do not edit it directly, but edit the source file and rerun 'make'
 */

#define REP_CACHE_DB_SQL \
  "pragma auto_vacuum = 1; "\
  "create table rep_cache (hash text not null primary key, "\
  "                        revision integer not null, "\
  "                        offset integer not null, "\
  "                        size integer not null, "\
  "                        expanded_size integer not null); "\
  ""
