all: ogre ois mocha rbgui

ogre:
	echo 'Type: cd ogre; ./bootstrap && ./configure && make -s && su -c "make -s install"; cd ..'
ois:
	echo 'Type: cd ois; ./bootstrap && ./configure && make -s && su -c "make -s install"; cd ..'
mocha:
	echo 'TODO'
rbgui:
	echo 'TODO'
