# Find the Apache Portable Runtime and APR-util libraries
#
# This module defines
#
#  APR_INCLUDE_DIR, where to find apr.h
#  APR_LIBRARY, the apr library
#
# It also defines, and can optionally require
#
#  APU_INCLUDE_DIR, where to find apu.h
#  APU_LIBRARY, the apr-util library

OPTION(REQUIRE_APR_UTIL "Require that FindAPR.cmake locate both APR and APR-util for success" ON)

FIND_PATH(APR_INCLUDE_DIR NAMES apr.h PATH_SUFFIXES apr-1)

FIND_LIBRARY(APR_LIBRARY NAMES apr-1 apr-1.0)

FIND_PATH(APU_INCLUDE_DIR NAMES apu.h PATH_SUFFIXES apr-1)

FIND_LIBRARY(APU_LIBRARY NAMES aprutil-1 aprutil-1.0)

SET(PACKAGE_HANDLE_VARS APR_INCLUDE_DIR APR_LIBRARY)
IF(REQUIRE_APR_UTIL)
	SET(PACKAGE_HANDLE_VARS ${PACKAGE_HANDLE_VARS} APU_INCLUDE_DIR APU_LIBRARY)
ENDIF(REQUIRE_APR_UTIL)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(APR DEFAULT_MSG ${PACKAGE_HANDLE_VARS})

MARK_AS_ADVANCED(APR_INCLUDE_DIR APR_LIBRARY APU_INCLUDE_DIR APU_LIBRARY)

