# Automate putting variables from tests into a config.h.in file,
# and otherwise wrap check macros in extra logic as needed

INCLUDE(CheckFunctionExists)
INCLUDE(CheckIncludeFiles)
INCLUDE(CheckIncludeFileCXX)
INCLUDE(CheckTypeSize)
INCLUDE(CheckLibraryExists)
INCLUDE(ResolveCompilerPaths)

MACRO(SVN_FUNCTION_EXISTS function var)
  CHECK_FUNCTION_EXISTS(${function} ${var})
  if(SVN_CONFIG_H_FILE)
     FILE(APPEND ${SVN_CONFIG_H_FILE} "#cmakedefine ${var} 1\n")
  endif(SVN_CONFIG_H_FILE)
ENDMACRO(SVN_FUNCTION_EXISTS)

MACRO(SVN_INCLUDE_FILE filename var)
  CHECK_INCLUDE_FILE(${filename} ${var})
  if(SVN_CONFIG_H_FILE)
     FILE(APPEND ${SVN_CONFIG_H_FILE} "#cmakedefine ${var} 1\n")
  endif(SVN_CONFIG_H_FILE)
ENDMACRO(SVN_INCLUDE_FILE)

MACRO(SVN_INCLUDE_FILE_CXX filename var)
  CHECK_INCLUDE_FILE_CXX(${filename} ${var})
  if(SVN_CONFIG_H_FILE)
     FILE(APPEND ${SVN_CONFIG_H_FILE} "#cmakedefine ${var} 1\n")
  endif(SVN_CONFIG_H_FILE)
ENDMACRO(SVN_INCLUDE_FILE_CXX)

MACRO(SVN_TYPE_SIZE typename var)
  CHECK_TYPE_SIZE(${typename} ${var})
  if(SVN_CONFIG_H_FILE)
     FILE(APPEND ${SVN_CONFIG_H_FILE} "#cmakedefine HAVE_${var} 1\n")
  endif(SVN_CONFIG_H_FILE)
ENDMACRO(SVN_TYPE_SIZE)

MACRO(SVN_CHECK_LIBRARY targetname lname func)
	IF(NOT ${targetname}_LIBRARY)
		CHECK_LIBRARY_EXISTS(${lname} ${func} "" HAVE_${targetname}_${lname})
		IF(HAVE_${targetname}_${lname})
			RESOLVE_LIBRARIES (${targetname}_LIBRARY "-l${lname}")
			SET(${targetname}_LINKOPT "-l${lname}")
			if(SVN_CONFIG_H_FILE)
				FILE(APPEND ${SVN_CONFIG_H_FILE} "#cmakedefine HAVE_LIB${targetname} 1\n")
			endif(SVN_CONFIG_H_FILE)
		ENDIF(HAVE_${targetname}_${lname})
	ENDIF(NOT ${targetname}_LIBRARY)
ENDMACRO(SVN_CHECK_LIBRARY lname func)
