/*                      
 * BRL-CAD
 *
 * Copyright (c) 2010 United States Government as represented by
 * the U.S. Army Research Laboratory.
 *
 * This library is free software you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * version 2.1 as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this file see the file named COPYING for more
 * information.
 */
   
 /******************************************************************/
 /******* THIS FILE WAS AUTO GENERATED BY RT3's BUILD SYSTEM *******/
 /************************** DO NOT EDIT! **************************/
 /******************************************************************/

#ifndef __GS_H__
#define __GS_H__

#include "GeometryService.h"
#include "DataManager.h"
#include "DbObjectManifest.h"
#include "GeometryProcessor.h"
#include "Session.h"
#include "SessionManager.h"
#include "Account.h"
#include "AccountManager.h"

#endif /* __GS_H__ */

// Local Variables: ***
// mode: C++ ***
// tab-width: 8 ***
// c-basic-offset: 2 ***
// indent-tabs-mode: t ***
// End: ***
// ex: shiftwidth=2 tabstop=8
