SET (RT3_FILE_HEADER "/*                      
 * BRL-CAD
 *
 * Copyright (c) 2010 United States Government as represented by
 * the U.S. Army Research Laboratory.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * version 2.1 as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this file; see the file named COPYING for more
 * information.
 */
")

SET (RT3_FILE_AUTOGEN_STATEMENT "   
 /******************************************************************/
 /******* THIS FILE WAS AUTO GENERATED BY RT3's BUILD SYSTEM *******/
 /************************** DO NOT EDIT! **************************/
 /******************************************************************/
")
 


SET (RT3_FILE_FOOTER "// Local Variables: ***
// mode: C++ ***
// tab-width: 8 ***
// c-basic-offset: 2 ***
// indent-tabs-mode: t ***
// End: ***
// ex: shiftwidth=2 tabstop=8
")



#
# RT3_PROJECT stuff.
#

MACRO(RT3_PROJECT PROJNAME)
    PROJECT(${PROJNAME})
    
    STRING(TOUPPER ${PROJECT_NAME} NAME_UPPER)
    
    #Make a var that points to the dir where the lib header is
    SET(${PROJECT_NAME}_PROJECT_DIR ${PROJECT_SOURCE_DIR} CACHE INTERNAL "")
    SET(${NAME_UPPER}_PROJECT_DIR ${PROJECT_SOURCE_DIR} CACHE INTERNAL "")    
    #MESSAGE(STATUS "${PROJECT_NAME}_PROJECT_DIR = ${${PROJECT_NAME}_PROJECT_DIR}")
    #MESSAGE(STATUS "${NAME_UPPER}_PROJECT_DIR = ${${NAME_UPPER}_PROJECT_DIR}")
        
    SET(${NAME_UPPER}_INCLUDE_DIRS ${GLOBAL_INCLUDE_DIRS}) #Global included by default
    SET(${NAME_UPPER}_LINK_LIBS)

    SET(${NAME_UPPER}_SOURCES)
    SET(${NAME_UPPER}_INST_HEADERS)
    SET(${NAME_UPPER}_NOINST_HEADERS)
    SET(${NAME_UPPER}_QT_INST_HEADERS)
    SET(${NAME_UPPER}_QT_NOINST_HEADERS)

    SET(${NAME_UPPER}_ALL_INST_HEADERS)
ENDMACRO(RT3_PROJECT FILENAME)

##Macros for building RT3_PROJECT variables
MACRO(RT3_PROJECT_ADD VARNAME)
    STRING(TOUPPER ${PROJECT_NAME} NAME_UPPER)
 
    FOREACH (tFile ${ARGN})
        SET(${NAME_UPPER}_${VARNAME} ${${NAME_UPPER}_${VARNAME}} ${tFile})
    ENDFOREACH (tFile)
ENDMACRO(RT3_PROJECT_ADD)

MACRO(RT3_PROJECT_ADD_INCLUDE_DIRS)    
        RT3_PROJECT_ADD("INCLUDE_DIRS" ${ARGN})
ENDMACRO(RT3_PROJECT_ADD_INCLUDE_DIRS)

MACRO(RT3_PROJECT_ADD_LIBS)    
        RT3_PROJECT_ADD("LINK_LIBS" ${ARGN})
ENDMACRO(RT3_PROJECT_ADD_LIBS)

MACRO(RT3_PROJECT_ADD_SOURCES)    
        RT3_PROJECT_ADD("SOURCES" ${ARGN})
ENDMACRO(RT3_PROJECT_ADD_SOURCES)

MACRO(RT3_PROJECT_ADD_INST_HEADERS)    
        RT3_PROJECT_ADD("INST_HEADERS" ${ARGN})
ENDMACRO(RT3_PROJECT_ADD_INST_HEADERS)

MACRO(RT3_PROJECT_ADD_NOINST_HEADERS)    
        RT3_PROJECT_ADD("NOINST_HEADERS" ${ARGN})
ENDMACRO(RT3_PROJECT_ADD_NOINST_HEADERS)

MACRO(RT3_PROJECT_ADD_QT_INST_HEADERS)    
        RT3_PROJECT_ADD("QT_INST_HEADERS" ${ARGN})
ENDMACRO(RT3_PROJECT_ADD_QT_INST_HEADERS)

MACRO(RT3_PROJECT_ADD_QT_NOINST_HEADERS)    
        RT3_PROJECT_ADD("QT_NOINST_HEADERS" ${ARGN})
ENDMACRO(RT3_PROJECT_ADD_QT_NOINST_HEADERS)

##Macro for writing the library's public header file
MACRO(MAKE_LIBRARY_HEADER_FILE)

    SET(FILENAME "${PROJECT_NAME}.h")
    STRING (TOUPPER ${FILENAME} FILENAME_UPPER)
    
    #Build the __include__ name    
    STRING (REPLACE "." "_" INCLUDE_NAME ${FILENAME_UPPER})
    SET(INCLUDE_NAME "__${INCLUDE_NAME}__")
        
    FILE(WRITE ${FILENAME} ${RT3_FILE_HEADER})
    FILE(APPEND ${FILENAME} ${RT3_FILE_AUTOGEN_STATEMENT})
    FILE(APPEND ${FILENAME} "\n")
    FILE(APPEND ${FILENAME} "#ifndef ${INCLUDE_NAME}\n")
    FILE(APPEND ${FILENAME} "#define ${INCLUDE_NAME}\n")
    FILE(APPEND ${FILENAME} "\n")
 
    FOREACH (headerFile ${${NAME_UPPER}_ALL_INST_HEADERS})
        FILE(APPEND ${FILENAME} "#include \"${headerFile}\"\n")
    ENDFOREACH (headerFile)
 
    FILE(APPEND ${FILENAME} "\n")
    FILE(APPEND ${FILENAME} "#endif /* ${INCLUDE_NAME} */\n\n")
    FILE(APPEND ${FILENAME} ${RT3_FILE_FOOTER})
ENDMACRO(MAKE_LIBRARY_HEADER_FILE)

##Macro to print out the project's config
MACRO(RT3_PROJECT_PRINT)
    STRING(TOUPPER ${PROJECT_NAME} NAME_UPPER)
    
    MESSAGE(STATUS "\tConfiguration for '${PROJECT_NAME}':")
    
    IF(${NAME_UPPER}_INCLUDE_DIRS)
        MESSAGE(STATUS "\t\t'${PROJECT_NAME}' include dirs:  ${${NAME_UPPER}_INCLUDE_DIRS}")
    ELSE(${NAME_UPPER}_INCLUDE_DIRS)
        MESSAGE(STATUS "\t\t'${PROJECT_NAME}' has no include dirs.")
    ENDIF(${NAME_UPPER}_INCLUDE_DIRS)
    
    IF(${NAME_UPPER}_LINK_LIBS)
        MESSAGE(STATUS "\t\t'${PROJECT_NAME}' linked libraries:   ${${NAME_UPPER}_LINK_LIBS}")
    ELSE(${NAME_UPPER}_LINK_LIBS)
        MESSAGE(STATUS "\t\t'${PROJECT_NAME}' has no linked libraries.")
    ENDIF(${NAME_UPPER}_LINK_LIBS)
 
    IF(${NAME_UPPER}_SOURCES)
        MESSAGE(STATUS "\t\t'${PROJECT_NAME}' source files:   ${${NAME_UPPER}_SOURCES}")
    ELSE(${NAME_UPPER}_SOURCES)
        MESSAGE(STATUS "\t\t'${PROJECT_NAME}' has no source files!")
    ENDIF(${NAME_UPPER}_SOURCES)
    
    
ENDMACRO(RT3_PROJECT_PRINT)

##Macro to build the project as a library
MACRO(RT3_PROJECT_BUILD_LIB LIBNAME)
    STRING(TOUPPER ${PROJECT_NAME} NAME_UPPER)
    
    INCLUDE_DIRECTORIES(${${NAME_UPPER}_INCLUDE_DIRS})
    
    qt4_wrap_cpp(${NAME_UPPER}_MOCCED_HEADERS ${${NAME_UPPER}_QT_INST_HEADERS} ${${NAME_UPPER}_QT_NOINST_HEADERS})

    SET(${NAME_UPPER}_ALL_INST_HEADERS ${${NAME_UPPER}_INST_HEADERS} ${${NAME_UPPER}_QT_INST_HEADERS})

    MAKE_LIBRARY_HEADER_FILE()

    RT3_PROJECT_PRINT()
    ADD_LIBRARY (${LIBNAME} SHARED ${${NAME_UPPER}_SOURCES})
    TARGET_LINK_LIBRARIES(${LIBNAME}  ${${NAME_UPPER}_LINK_LIBS})
    
    #ADD TO GLOBAL
    SET(GLOBAL_INCLUDE_DIRS ${GLOBAL_INCLUDE_DIRS} ${${PROJECT_NAME}_PROJECT_DIR} CACHE INTERNAL "")
    
    MESSAGE(STATUS "\tDone.")
ENDMACRO(RT3_PROJECT_BUILD_LIB)

##Macro to build the project as an Executable
MACRO(RT3_PROJECT_BUILD_EXE EXENAME)
    STRING(TOUPPER ${PROJECT_NAME} NAME_UPPER)
    
    INCLUDE_DIRECTORIES(${${NAME_UPPER}_INCLUDE_DIRS})
    
    qt4_wrap_cpp(${NAME_UPPER}_MOCCED_HEADERS ${${NAME_UPPER}_QT_INST_HEADERS} ${${NAME_UPPER}_QT_NOINST_HEADERS})

    SET(${NAME_UPPER}_ALL_INST_HEADERS ${${NAME_UPPER}_INST_HEADERS} ${${NAME_UPPER}_QT_INST_HEADERS})

    RT3_PROJECT_PRINT()
    ADD_EXECUTABLE (${EXENAME} ${${NAME_UPPER}_SOURCES})
    TARGET_LINK_LIBRARIES(${EXENAME}  ${${NAME_UPPER}_LINK_LIBS})

    MESSAGE(STATUS "\tDone.")
ENDMACRO(RT3_PROJECT_BUILD_EXE)











